# Generated by Django 2.1.3 on 2019-04-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_element', models.CharField(max_length=30)),
                ('nom_element', models.CharField(max_length=30)),
                ('etat_element', models.CharField(max_length=30)),
                ('gravite', models.CharField(max_length=30)),
                ('date_apparition', models.DateTimeField()),
                ('date_disparition_systeme', models.DateTimeField()),
            ],
        ),
    ]
