# Generated by Django 2.1.3 on 2019-04-24 14:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('configSalle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationSalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AlterModelOptions(
            name='uce',
            options={'ordering': ['configurationSalle']},
        ),
        migrations.AddField(
            model_name='uce',
            name='configurationSalle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configSalle.ConfigurationSalle'),
        ),
    ]
