# Generated by Django 2.1.3 on 2019-04-24 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configSalle', '0003_auto_20190424_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uce',
            name='configurationSalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configSalle.ConfigurationSalle'),
        ),
    ]
