# Generated by Django 2.1.3 on 2019-04-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configSalle', '0004_auto_20190424_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationsalle',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
