# Generated by Django 2.1.3 on 2019-05-14 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configSalle', '0005_auto_20190424_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uce',
            name='configurationSalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confUce', to='configSalle.ConfigurationSalle'),
        ),
    ]
