# Generated by Django 2.1.3 on 2019-05-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configSalle', '0006_auto_20190514_1711'),
        ('configSalle', '0006_auto_20190514_1728'),
    ]

    operations = [
    ]
