# Generated by Django 2.1.3 on 2019-03-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appelant', models.CharField(max_length=30)),
                ('appele', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('type', models.CharField(max_length=30)),
                ('duree', models.IntegerField()),
                ('liberation', models.CharField(max_length=30)),
                ('fsx_appelant', models.CharField(default='xxxxx', max_length=30)),
                ('fsx_appele', models.CharField(max_length=30)),
            ],
        ),
    ]
