# Generated by Django 2.1.3 on 2019-04-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appel',
            name='etat',
            field=models.CharField(default='xxxxx', max_length=30),
        ),
        migrations.AlterField(
            model_name='appel',
            name='fsx_appele',
            field=models.CharField(default='xxxxx', max_length=30),
        ),
    ]
