# Generated by Django 2.1.3 on 2019-04-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_auto_20190401_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appel',
            old_name='fsx_appelant',
            new_name='line_appelante',
        ),
        migrations.RenameField(
            model_name='appel',
            old_name='fsx_appele',
            new_name='line_appele',
        ),
        migrations.AddField(
            model_name='appel',
            name='fx',
            field=models.CharField(default='fx_xxxx', max_length=30),
        ),
    ]
