# Generated by Django 2.1.3 on 2019-04-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_auto_20190409_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appel',
            name='fx',
        ),
        migrations.AddField(
            model_name='appel',
            name='fx_entrant',
            field=models.CharField(default='fx_xxxx_e', max_length=30),
        ),
        migrations.AddField(
            model_name='appel',
            name='fx_sortant',
            field=models.CharField(default='fx_xxxx_s', max_length=30),
        ),
    ]
