# Generated by Django 2.1.3 on 2019-05-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_auto_20190409_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumExterieur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_elts', models.CharField(max_length=4)),
                ('id_lilas', models.CharField(max_length=4)),
                ('numero', models.CharField(max_length=15)),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
    ]
