# Generated by Django 2.1.3 on 2019-05-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0007_auto_20190503_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faisceau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_elts', models.CharField(max_length=4)),
                ('id_lilas', models.CharField(max_length=4)),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
    ]
