# Generated by Django 2.1.3 on 2019-05-21 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0008_faisceau'),
    ]

    operations = [
        migrations.CreateModel(
            name='LIF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_elts', models.CharField(max_length=4)),
                ('id_lilas', models.CharField(max_length=4)),
                ('nom', models.CharField(max_length=30)),
                ('faisceau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.Faisceau')),
            ],
        ),
    ]
