# Generated by Django 2.2.7 on 2019-11-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0010_auto_20190522_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faisceau',
            options={'verbose_name_plural': 'Faisceaux'},
        ),
        migrations.AlterModelOptions(
            name='lif',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='numexterieur',
            options={'ordering': ['nom']},
        ),
    ]
