# Generated by Django 2.1.3 on 2019-12-04 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0011_auto_20191126_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='appel',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.Date'),
        ),
    ]
