# Generated by Django 2.1.3 on 2019-12-04 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0012_auto_20191204_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='appel',
            name='heure',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
    ]
