# Generated by Django 2.1.3 on 2019-12-04 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0014_auto_20191204_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appel',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appel', to='communication.Date'),
        ),
    ]
